/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.allInterfaces.action3saisien;


import com.classes.action3saisie.Demande;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author RAP
 */
public class SaisieParOperateur extends javax.swing.JInternalFrame {
    
    private final String comb_demarche = "Séléctionner une démarche";
    //static String comb_annee_saisie = "Séléctionner une année";
    private final String com_critere_date = "Séléctionner une critère de date";
    private final String com_critere_par_date = "Par Date";
    private final String com_critere_intervale_de_date = "Intervale de date";
    String dateDebut = "";
    String dateFin = "";
    
    private String BDD_HOST = "";
    private Integer BDD_PORT;
    private String BDD_DBNAME = "";
    private String BDD_USER = "";
    private String BDD_PWD = "";
    private String demarche = "";
    /**
     * Creates new form SaisieParOperateur
     */
    public SaisieParOperateur(String HOST, Integer PORT, String DBNAME, String USER, String PWD, String demarche) {
        
        this.BDD_HOST = HOST;
        this.BDD_PORT = PORT;
        this.BDD_DBNAME = DBNAME;
        this.BDD_USER = USER;
        this.BDD_PWD = PWD;
        
        
        initComponents();
        
        this.j_date_debut.setEnabled(false);
        this.j_comb_demarche.removeAllItems();
        this.j_comb_demarche.addItem(demarche);
        this.demarche = demarche;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        j_panel_saisie_par_op = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        j_table_saisie_par_operateur = new javax.swing.JTable();
        j_label_date_saisie = new javax.swing.JLabel();
        j_date_debut = new com.toedter.calendar.JDateChooser();
        j_label_annee_saisie1 = new javax.swing.JLabel();
        j_comb_demarche = new javax.swing.JComboBox<>();
        j_bouton_search = new javax.swing.JButton();
        j_button_reset = new javax.swing.JButton();
        j_label_date_saisie1 = new javax.swing.JLabel();
        j_date_fin = new com.toedter.calendar.JDateChooser();
        j_comb_select_critere_date = new javax.swing.JComboBox<>();
        j_label_annee_saisie2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Saisie Par Opérateur");

        j_table_saisie_par_operateur.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Opérateur", "Commune", "Nombre de Saisie"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(j_table_saisie_par_operateur);
        if (j_table_saisie_par_operateur.getColumnModel().getColumnCount() > 0) {
            j_table_saisie_par_operateur.getColumnModel().getColumn(2).setResizable(false);
        }

        j_label_date_saisie.setText("Date de début");

        j_date_debut.setDateFormatString("dd/MM/yyyy");

        j_label_annee_saisie1.setText("Démarche");

        j_comb_demarche.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Séléctionner une démarche", "OGCF", "OCFM" }));

        j_bouton_search.setText("Rechercher");
        j_bouton_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_bouton_searchActionPerformed(evt);
            }
        });

        j_button_reset.setText("Réinitialiser");

        j_label_date_saisie1.setText("Date de fin");

        j_date_fin.setDateFormatString("dd/MM/yyyy");
        j_date_fin.setEnabled(false);

        j_comb_select_critere_date.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Séléctionner une critère de date", "Par Date", "Intervale de date" }));
        j_comb_select_critere_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_comb_select_critere_dateActionPerformed(evt);
            }
        });

        j_label_annee_saisie2.setText("Critère Date");

        javax.swing.GroupLayout j_panel_saisie_par_opLayout = new javax.swing.GroupLayout(j_panel_saisie_par_op);
        j_panel_saisie_par_op.setLayout(j_panel_saisie_par_opLayout);
        j_panel_saisie_par_opLayout.setHorizontalGroup(
            j_panel_saisie_par_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j_panel_saisie_par_opLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(j_panel_saisie_par_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(j_panel_saisie_par_opLayout.createSequentialGroup()
                        .addComponent(j_bouton_search)
                        .addGap(18, 18, 18)
                        .addComponent(j_button_reset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(j_panel_saisie_par_opLayout.createSequentialGroup()
                        .addGroup(j_panel_saisie_par_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(j_panel_saisie_par_opLayout.createSequentialGroup()
                                .addComponent(j_label_date_saisie1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(j_date_fin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(j_panel_saisie_par_opLayout.createSequentialGroup()
                                .addComponent(j_label_date_saisie, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(j_date_debut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(j_panel_saisie_par_opLayout.createSequentialGroup()
                                .addComponent(j_label_annee_saisie1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(j_comb_demarche, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, j_panel_saisie_par_opLayout.createSequentialGroup()
                                .addComponent(j_label_annee_saisie2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(j_comb_select_critere_date, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 18, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        j_panel_saisie_par_opLayout.setVerticalGroup(
            j_panel_saisie_par_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j_panel_saisie_par_opLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(j_panel_saisie_par_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j_comb_demarche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j_label_annee_saisie1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(j_panel_saisie_par_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j_comb_select_critere_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j_label_annee_saisie2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(j_panel_saisie_par_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(j_label_date_saisie)
                    .addComponent(j_date_debut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(j_panel_saisie_par_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(j_label_date_saisie1)
                    .addComponent(j_date_fin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(j_panel_saisie_par_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j_bouton_search)
                    .addComponent(j_button_reset))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(j_panel_saisie_par_opLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 79, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(j_panel_saisie_par_op, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(j_panel_saisie_par_op, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(274, 274, 274))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

 
    
    private void j_bouton_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_bouton_searchActionPerformed

        String demarche = (String)this.j_comb_demarche.getSelectedItem();
        DateFormat df = new SimpleDateFormat("dd/MM/YYYY");
        String val_critere = this.j_comb_select_critere_date.getSelectedItem().toString();
        
        if(demarche.equals(comb_demarche)){
            
            System.out.println("Veuillez séléctionner une démarche");
            JOptionPane.showMessageDialog(null, "Veuillez séléctionner une démarche !","Séléctionner une démarche", JOptionPane.INFORMATION_MESSAGE);

        }else{
            
            if(val_critere.equals(com_critere_date)){
                System.out.println("Veuillez séléctionner une critère de date");
                JOptionPane.showMessageDialog(null, "Veuillez séléctionner une critère de date!","Séléctionner critère de date", JOptionPane.INFORMATION_MESSAGE);
            }else{
                         
                if(val_critere.equals(com_critere_par_date)){

                    if(this.j_date_debut.getDate() == null){
                        System.out.println("Veuillez remplir le date fin");
                        JOptionPane.showMessageDialog(null, "Date début de saisie vide ou incorrect !","Erreur lors remplissage date de début de saisie", JOptionPane.INFORMATION_MESSAGE); 
                    }else{

                        dateDebut += df.format(this.j_date_debut.getDate());
                        //System.out.println("ok simple date : "+ com_critere_par_date + dateDebut);
                        
                        HashMap <String, String> saisieDesOperateurs  = new Demande(this.BDD_HOST, this.BDD_PORT, this.BDD_DBNAME, this.BDD_USER, this.BDD_PWD).getSimpleSaisieParOperateur(dateDebut, this.demarche);
                        System.out.println("ok simple date : "+ saisieDesOperateurs);
                    }

                     
                }else{
                    
                    
                    if(this.j_date_debut.getDate() == null && this.j_date_fin.getDate() == null){
                        System.out.println("Veuillez remplir les dates (début et fin) de saisie");
                        JOptionPane.showMessageDialog(null, "Dates (début et/ou fin) de saisie vide ou incorrect !","Séléctionner les dates de saisie", JOptionPane.INFORMATION_MESSAGE); 
                    }else if(this.j_date_debut.getDate() == null){
                        System.out.println("Veuillez remplir le date début");
                        JOptionPane.showMessageDialog(null, "Date début de saisie vide ou incorrect !","Erreur lors remplissage date début de saisie", JOptionPane.INFORMATION_MESSAGE); 
                    }else if(this.j_date_fin.getDate() == null){
                        System.out.println("Veuillez remplir le date fin");
                        JOptionPane.showMessageDialog(null, "Date fin de saisie vide ou incorrect !","SErreur lors remplissage date Fin de saisie", JOptionPane.INFORMATION_MESSAGE); 
                    }else{
                        
                        dateDebut += df.format(this.j_date_debut.getDate());
                        dateFin += df.format(this.j_date_fin.getDate());
                        //System.out.println("ok intervale : \n\n"+ "date début = "+ dateDebut + " date fin = " + dateFin);
                        
                        //String d  = new Demande().getSaisieParOperateur(dateDebut, dateFin);
                        HashMap <String, String> saisieDesOperateursBetweenTwoDate  = new Demande(this.BDD_HOST, this.BDD_PORT, this.BDD_DBNAME, this.BDD_USER, this.BDD_PWD).getSaisieParOperateur(dateDebut, dateFin, false);
                        System.out.println("ok intervale date : "+ saisieDesOperateursBetweenTwoDate);
                    }
                    
                    
                }

            }
        
        }
    
    }//GEN-LAST:event_j_bouton_searchActionPerformed

    private void j_comb_select_critere_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_comb_select_critere_dateActionPerformed
        
        this.j_date_debut.setEnabled(false);
        this.j_date_fin.setEnabled(false);
        String selectedValue = this.j_comb_select_critere_date.getSelectedItem().toString();
        
        
        switch(selectedValue){
            
            case  com_critere_date : 

                this.j_date_debut.setCalendar(null);
                this.j_date_fin.setCalendar(null);
                this.j_date_debut.setEnabled(false);
                this.j_date_fin.setEnabled(false);
                break;
                
            case  com_critere_intervale_de_date : 
                
                this.j_date_debut.setEnabled(true);
                this.j_date_fin.setEnabled(true);
                break;
            
            default :
                
                this.j_date_fin.setCalendar(null);
                this.j_date_debut.setEnabled(true);
                break;
        }

    }//GEN-LAST:event_j_comb_select_critere_dateActionPerformed


    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton j_bouton_search;
    private javax.swing.JButton j_button_reset;
    private javax.swing.JComboBox<String> j_comb_demarche;
    private javax.swing.JComboBox<String> j_comb_select_critere_date;
    private com.toedter.calendar.JDateChooser j_date_debut;
    private com.toedter.calendar.JDateChooser j_date_fin;
    private javax.swing.JLabel j_label_annee_saisie1;
    private javax.swing.JLabel j_label_annee_saisie2;
    private javax.swing.JLabel j_label_date_saisie;
    private javax.swing.JLabel j_label_date_saisie1;
    private javax.swing.JPanel j_panel_saisie_par_op;
    private javax.swing.JTable j_table_saisie_par_operateur;
    // End of variables declaration//GEN-END:variables
}
