/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.allInterfaces.action3saisies;


import com.classes.action3saisie.Formats;
import com.classes.action3saisie.Querry;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RAP
 */
public class Consultations extends javax.swing.JInternalFrame {
    
    private final DefaultTableModel modeleAnomaliesCategoriesTerrain;
    private final DefaultTableModel modeleAnomaliesAvis;
    private final DefaultTableModel modeleAnomaliesCqiNieau1;
    List <String[]> saisieDesOperateurs = null;
    private String BDD_HOST = "";
    private Integer BDD_PORT;
    private String BDD_DBNAME = "";
    private String BDD_USER = "";
    private String BDD_PWD = "";
    private String demarche = "";
    
    String[] EnTeteTableauAnomaliesCategoriesTerrain = {"Région", "Commune", "Numéro demande", "Code Parcelle", "Annulé ?", "En opposition ?", "Validation CQI niveau 1"};
    
    String[] EnTeteTableauAnomaliesAvisCRLEtOpposition = {"Opération", "Région", "Commune", "Numéro demande", "Code Parcelle", "Avis CRL", "En opposition ?","Annulé ?", "Validation CQI niveau 1", "Validateur", "Opérateur Traiteur", "N° de Lot" };
    
    
    String[] EnTeteTableauAnomaliesCqiNiveau1 = {"Opération", "Région", "Commune", "Numéro demande", "Code Parcelle", "Avis CRL", "En opposition ?", "Validation CQI niveau 1", "Annulé ?"};
        
    /**
     * Creates new form SaisieParOperateur
     */
    public Consultations(String HOST, Integer PORT, String DBNAME, String PWD, String USER, String DEM) {
        
        this.BDD_HOST = HOST;
        this.BDD_PORT = PORT;
        this.BDD_DBNAME = DBNAME;
        this.BDD_USER = USER;
        this.BDD_PWD = PWD;
        this.demarche = Formats.ConvertOcfmToOcm(DEM);
        
        initComponents();
        
        
        this.txt_information.setVisible(false);
        this.txt_information_valide_cqi_1.setVisible(false);
        this.txt_information_anomalies_actegories.setVisible(false);
        
        modeleAnomaliesCategoriesTerrain = new DefaultTableModel();
        
        
        
        if (modeleAnomaliesCategoriesTerrain.getRowCount() <=0) {
            this.J_Button_Export_AnomaliesCategories.setEnabled(false);
        }
        CreateTables(EnTeteTableauAnomaliesCategoriesTerrain,modeleAnomaliesCategoriesTerrain, J_Table_Anomalies_Categories_Terrain );
        
        
        
        
        modeleAnomaliesAvis =  new DefaultTableModel();
        if (modeleAnomaliesAvis.getRowCount() <=0) {
            this.J_Button_Export_Avis_CRL.setEnabled(false);
        }
        CreateTables(EnTeteTableauAnomaliesAvisCRLEtOpposition,modeleAnomaliesAvis, J_Table_Anomalies_Avis_CRL_et_Opposition );
        
        
        
        
        modeleAnomaliesCqiNieau1 =  new DefaultTableModel();
        if (modeleAnomaliesCqiNieau1.getRowCount() <=0) {
            this.J_Button_Export_valide_cq_niveau_1.setEnabled(false);
        }
        CreateTables(EnTeteTableauAnomaliesCqiNiveau1,modeleAnomaliesCqiNieau1, J_Table_valide_cq_niveau_1 );
        
        
        

    }
    
    
    private Boolean CreateTables (String[] enTete, DefaultTableModel models, JTable tables){

        for (String enTete1 : enTete) {
            models.addColumn(enTete1);
        }
        
        if(enTete.length != models.getColumnCount()){
            return false;
        }
        
        
        tables.setModel(models);
        
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu_Click_Droit = new javax.swing.JPopupMenu();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        J_Table_Anomalies_Categories_Terrain = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        search_anomalies_actegories = new javax.swing.JButton();
        J_Button_Export_AnomaliesCategories = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        txt_information_anomalies_actegories = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        J_Table_autoncontrole_op = new javax.swing.JTable();
        jPanel17 = new javax.swing.JPanel();
        txt_information_autocontrole_OP = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        J_Button_Export_autocontrole_op = new javax.swing.JButton();
        search_autocontrole_op = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        J_Table_valide_cq_niveau_1 = new javax.swing.JTable();
        jPanel13 = new javax.swing.JPanel();
        txt_information_valide_cqi_1 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        J_Button_Export_valide_cq_niveau_1 = new javax.swing.JButton();
        search_valide_cq_niveau_1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        J_Button_Export_Avis_CRL = new javax.swing.JButton();
        search_anomalies_avis_CRL_et_Opposition = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        txt_information = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        J_Table_Anomalies_Avis_CRL_et_Opposition = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Contrôles Des Saisies");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/logo geox2~2.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Consultations");

        J_Table_Anomalies_Categories_Terrain.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        J_Table_Anomalies_Categories_Terrain.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        J_Table_Anomalies_Categories_Terrain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                J_Table_Anomalies_Categories_TerrainMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(J_Table_Anomalies_Categories_Terrain);

        search_anomalies_actegories.setText("Rechercher ...");
        search_anomalies_actegories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_anomalies_actegoriesActionPerformed(evt);
            }
        });

        J_Button_Export_AnomaliesCategories.setText("Exporter");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(search_anomalies_actegories)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(J_Button_Export_AnomaliesCategories)
                .addGap(157, 157, 157))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search_anomalies_actegories)
                    .addComponent(J_Button_Export_AnomaliesCategories))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txt_information_anomalies_actegories.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        txt_information_anomalies_actegories.setText("jLabel2");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_information_anomalies_actegories, javax.swing.GroupLayout.DEFAULT_SIZE, 847, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_information_anomalies_actegories, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Listes demandeurs", jPanel1);

        J_Table_autoncontrole_op.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        J_Table_autoncontrole_op.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(J_Table_autoncontrole_op);

        txt_information_autocontrole_OP.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        txt_information_autocontrole_OP.setText("jLabel2");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_information_autocontrole_OP, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_information_autocontrole_OP, javax.swing.GroupLayout.PREFERRED_SIZE, 16, Short.MAX_VALUE)
                .addContainerGap())
        );

        J_Button_Export_autocontrole_op.setText("Exporter");

        search_autocontrole_op.setText("Rechercher ...");
        search_autocontrole_op.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_autocontrole_opActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(search_autocontrole_op)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(J_Button_Export_autocontrole_op)
                .addContainerGap(265, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search_autocontrole_op)
                    .addComponent(J_Button_Export_autocontrole_op)))
        );

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Autocontrôle Opérateurs", jPanel2);

        J_Table_valide_cq_niveau_1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        J_Table_valide_cq_niveau_1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(J_Table_valide_cq_niveau_1);

        txt_information_valide_cqi_1.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        txt_information_valide_cqi_1.setText("jLabel2");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_information_valide_cqi_1, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_information_valide_cqi_1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, Short.MAX_VALUE)
                .addContainerGap())
        );

        J_Button_Export_valide_cq_niveau_1.setText("Exporter");

        search_valide_cq_niveau_1.setText("Rechercher ...");
        search_valide_cq_niveau_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_valide_cq_niveau_1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(search_valide_cq_niveau_1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(J_Button_Export_valide_cq_niveau_1)
                .addContainerGap(265, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search_valide_cq_niveau_1)
                    .addComponent(J_Button_Export_valide_cq_niveau_1)))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Vlidé CQI niveau 1 ?", jPanel3);

        J_Button_Export_Avis_CRL.setText("Exporter");

        search_anomalies_avis_CRL_et_Opposition.setText("Rechercher ...");
        search_anomalies_avis_CRL_et_Opposition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_anomalies_avis_CRL_et_OppositionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(search_anomalies_avis_CRL_et_Opposition)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(J_Button_Export_Avis_CRL)
                .addContainerGap(220, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search_anomalies_avis_CRL_et_Opposition)
                    .addComponent(J_Button_Export_Avis_CRL)))
        );

        txt_information.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        txt_information.setText("jLabel2");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_information, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_information, javax.swing.GroupLayout.PREFERRED_SIZE, 16, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(51, 51, 51)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        J_Table_Anomalies_Avis_CRL_et_Opposition.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        J_Table_Anomalies_Avis_CRL_et_Opposition.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(J_Table_Anomalies_Avis_CRL_et_Opposition);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Avis CRL et Opposition", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(535, 535, 535)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void search_anomalies_actegoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_anomalies_actegoriesActionPerformed
        //System.out.println("Search catégories ...");
        DefaultTableModel tableau = (DefaultTableModel) J_Table_Anomalies_Categories_Terrain.getModel();
        Formats.resetTable(tableau);

        Object rowData[] = new Object[7];

        saisieDesOperateurs  = new Querry(this.BDD_HOST, this.BDD_PORT, this.BDD_DBNAME, this.BDD_USER, this.BDD_PWD, this.demarche).getAnomaliesSaisiesOPCategoriesTerrain(this.demarche, EnTeteTableauAnomaliesCategoriesTerrain);

        
        int nbreEnregistrement = saisieDesOperateurs.size();
        
        if (nbreEnregistrement <=0) {
            this.J_Button_Export_AnomaliesCategories.setEnabled(false);
            JOptionPane.showMessageDialog(null, "Aucun résultat trouvé", "", JOptionPane.INFORMATION_MESSAGE);
        }else{
            
            this.J_Button_Export_AnomaliesCategories.setEnabled(true);
            this.txt_information_anomalies_actegories.setText(nbreEnregistrement + " Enregistrement(s) trouvés - \nDont Catégories Terrain (Rizière, Cour, Etang, Etable, Boisement, ect.) non coché dans BDD.");
            this.txt_information_anomalies_actegories.setVisible(true);
            
            for (int a = 0; a < saisieDesOperateurs.size(); a++) {

                //for (int i = 0; i < EnTeteTableauAnomaliesCategoriesTerrain.length; i++) {

                    rowData[0] = " "+Formats.ConvertOcmToOcfm(saisieDesOperateurs.get(a)[0]).toUpperCase();
                    rowData[1] = saisieDesOperateurs.get(a)[1];
                    rowData[2] = saisieDesOperateurs.get(a)[2];
                    rowData[3] = saisieDesOperateurs.get(a)[3];
                    rowData[4] = saisieDesOperateurs.get(a)[4];
                    rowData[5] = saisieDesOperateurs.get(a)[5];
                    rowData[6] = saisieDesOperateurs.get(a)[6];

                    tableau.addRow(rowData);
                    //}

            }
            
        }
        

        

        
    }//GEN-LAST:event_search_anomalies_actegoriesActionPerformed

    private void search_anomalies_avis_CRL_et_OppositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_anomalies_avis_CRL_et_OppositionActionPerformed
        //System.out.println("Search catégories ...");
        DefaultTableModel tableau = (DefaultTableModel) J_Table_Anomalies_Avis_CRL_et_Opposition.getModel();
        Formats.resetTable(tableau);

        Object rowData[] = new Object[12];

        saisieDesOperateurs  = new Querry(this.BDD_HOST, this.BDD_PORT, this.BDD_DBNAME, this.BDD_USER, this.BDD_PWD, this.demarche).getAnomaliesOPAvisCRLetOpposition(this.demarche, EnTeteTableauAnomaliesCategoriesTerrain);

        int nbreEnregistrement = saisieDesOperateurs.size();
        
        
        if (nbreEnregistrement <=0) {
            this.J_Button_Export_Avis_CRL.setEnabled(false);
            JOptionPane.showMessageDialog(null, "Aucun résultat trouvé", "", JOptionPane.INFORMATION_MESSAGE);
        }else{
            
            this.J_Button_Export_Avis_CRL.setEnabled(true);
            this.txt_information.setText(nbreEnregistrement + " Enregistrement(s) trouvés - Dont avis CRL et/ou Opposition a comme valuer NULL dans BDD.");
            this.txt_information.setVisible(true);
            
            for (int a = 0; a < saisieDesOperateurs.size(); a++) {

                    rowData[0] = " "+Formats.ConvertOcmToOcfm(saisieDesOperateurs.get(a)[0]).toUpperCase();
                    rowData[1] = saisieDesOperateurs.get(a)[1].toUpperCase();
                    rowData[2] = saisieDesOperateurs.get(a)[2];
                    rowData[3] = saisieDesOperateurs.get(a)[3];
                    rowData[4] = saisieDesOperateurs.get(a)[4];
                    rowData[5] = saisieDesOperateurs.get(a)[5];
                    rowData[6] = saisieDesOperateurs.get(a)[6];
                    rowData[7] = saisieDesOperateurs.get(a)[7];
                    rowData[8] = saisieDesOperateurs.get(a)[8];
                    rowData[9] = saisieDesOperateurs.get(a)[9];
                    rowData[10] = saisieDesOperateurs.get(a)[10];
                    rowData[11] = saisieDesOperateurs.get(a)[11];

                    tableau.addRow(rowData);
            }
            
        }

    }//GEN-LAST:event_search_anomalies_avis_CRL_et_OppositionActionPerformed

    private void J_Table_Anomalies_Categories_TerrainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_J_Table_Anomalies_Categories_TerrainMouseClicked
        System.out.println("Clciked = " + evt.getSource());
        this.jPopupMenu_Click_Droit.setVisible(true);
        
    }//GEN-LAST:event_J_Table_Anomalies_Categories_TerrainMouseClicked

    private void search_valide_cq_niveau_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_valide_cq_niveau_1ActionPerformed
//System.out.println("Search catégories ...");
        DefaultTableModel tableau = (DefaultTableModel) J_Table_valide_cq_niveau_1.getModel();
        Formats.resetTable(tableau);

        Object rowData[] = new Object[9];

        saisieDesOperateurs  = new Querry(this.BDD_HOST, this.BDD_PORT, this.BDD_DBNAME, this.BDD_USER, this.BDD_PWD, this.demarche).getAnomaliesValChefEquipeNULL(this.demarche, EnTeteTableauAnomaliesCategoriesTerrain);

        int nbreEnregistrement = saisieDesOperateurs.size();
        
        
        if (nbreEnregistrement <=0) {
            this.J_Button_Export_valide_cq_niveau_1.setEnabled(false);
            JOptionPane.showMessageDialog(null, "Aucun résultat trouvé", "", JOptionPane.INFORMATION_MESSAGE);
        }else{
            
            this.J_Button_Export_valide_cq_niveau_1.setEnabled(true);
            this.txt_information_valide_cqi_1.setText(nbreEnregistrement + " Enregistrement(s) trouvés - Dont valeur CQI niveau 1 est NULL.");
            this.txt_information_valide_cqi_1.setVisible(true);
            
            for (int a = 0; a < saisieDesOperateurs.size(); a++) {

                    rowData[0] = " "+Formats.ConvertOcmToOcfm(saisieDesOperateurs.get(a)[0]).toUpperCase();
                    rowData[1] = saisieDesOperateurs.get(a)[1].toUpperCase();
                    rowData[2] = saisieDesOperateurs.get(a)[2];
                    rowData[3] = saisieDesOperateurs.get(a)[3];
                    rowData[4] = saisieDesOperateurs.get(a)[4];
                    rowData[5] = saisieDesOperateurs.get(a)[5];
                    rowData[6] = saisieDesOperateurs.get(a)[6];
                    rowData[7] = saisieDesOperateurs.get(a)[7];
                    rowData[8] = saisieDesOperateurs.get(a)[8];

                    tableau.addRow(rowData);
            }
            
        }
    }//GEN-LAST:event_search_valide_cq_niveau_1ActionPerformed

    private void search_autocontrole_opActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_autocontrole_opActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_autocontrole_opActionPerformed

 
    

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton J_Button_Export_AnomaliesCategories;
    private javax.swing.JButton J_Button_Export_Avis_CRL;
    private javax.swing.JButton J_Button_Export_autocontrole_op;
    private javax.swing.JButton J_Button_Export_valide_cq_niveau_1;
    private javax.swing.JTable J_Table_Anomalies_Avis_CRL_et_Opposition;
    private javax.swing.JTable J_Table_Anomalies_Categories_Terrain;
    private javax.swing.JTable J_Table_autoncontrole_op;
    private javax.swing.JTable J_Table_valide_cq_niveau_1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPopupMenu jPopupMenu_Click_Droit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton search_anomalies_actegories;
    private javax.swing.JButton search_anomalies_avis_CRL_et_Opposition;
    private javax.swing.JButton search_autocontrole_op;
    private javax.swing.JButton search_valide_cq_niveau_1;
    private javax.swing.JLabel txt_information;
    private javax.swing.JLabel txt_information_anomalies_actegories;
    private javax.swing.JLabel txt_information_autocontrole_OP;
    private javax.swing.JLabel txt_information_valide_cqi_1;
    // End of variables declaration//GEN-END:variables
}
