/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.allInterfaces.action3saisies;

import com.classes.action3saisie.Querry;
import java.awt.event.ItemEvent;
import java.io.File;
import java.sql.Connection;
import java.util.HashMap;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author RAP
 */
public class TraitementImportSaisieCroise extends javax.swing.JFrame {
    
    private static Connection connectDatabase;
    private static String BDD_HOST = "";
    private static Integer BDD_PORT;
    private static String BDD_DBNAME = "";
    private static String BDD_USER = "";
    private static String BDD_PWD = "";
    private static String type_operation;
    private final String c = "Séléctionner une critère de recherche";
    
    
    /**
     * Creates new form TraitementImportSaisieCroise
     * @param host
     * @param port
     * @param user
     * @param dbname
     * @param password
     * @param operation
     */
    public TraitementImportSaisieCroise(String host, Integer port, String dbname, String user, String password, String operation) {
        
        TraitementImportSaisieCroise.BDD_HOST = host;
        TraitementImportSaisieCroise.BDD_PORT = port;
        TraitementImportSaisieCroise.BDD_DBNAME = dbname;
        TraitementImportSaisieCroise.BDD_USER = user;
        TraitementImportSaisieCroise.BDD_PWD = password;
        TraitementImportSaisieCroise.type_operation = operation;
        
        
        initComponents();
        this.jlabel_base_source.setText("Base de données source : " + TraitementImportSaisieCroise.BDD_DBNAME);
        this.jpan_critere_entre_deux_date.setEnabled(false);
        this.jpan_critere_combo_lot_et_utilisateur.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanel_en_tete = new javax.swing.JPanel();
        jlabel_base_source = new javax.swing.JLabel();
        j_combo_critere = new javax.swing.JComboBox<>();
        jpan_critere_entre_deux_date = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jDate_fin = new com.toedter.calendar.JDateChooser();
        jDate_debut = new com.toedter.calendar.JDateChooser();
        jpan_critere_combo_lot_et_utilisateur = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        j_combo_select_critere = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        btn_valider_recherche = new javax.swing.JButton();
        jpanel_pers_physique = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_personne_phys = new javax.swing.JTable();
        jpanel_pers_morale = new javax.swing.JPanel();

        jpanel_en_tete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jpanel_en_tete.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N

        jlabel_base_source.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        jlabel_base_source.setText("jLabel1");
        jlabel_base_source.setFocusable(false);

        j_combo_critere.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        j_combo_critere.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Séléctionner une critère de recherche", "Par Date", "Intervale de date", "Par Utilisateurs", "Par Lot" }));
        j_combo_critere.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                j_combo_critereItemStateChanged(evt);
            }
        });

        jLabel1.setText("Date et Heure fin");

        jLabel2.setText("Date et Heure début");

        javax.swing.GroupLayout jpan_critere_entre_deux_dateLayout = new javax.swing.GroupLayout(jpan_critere_entre_deux_date);
        jpan_critere_entre_deux_date.setLayout(jpan_critere_entre_deux_dateLayout);
        jpan_critere_entre_deux_dateLayout.setHorizontalGroup(
            jpan_critere_entre_deux_dateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpan_critere_entre_deux_dateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpan_critere_entre_deux_dateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpan_critere_entre_deux_dateLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDate_fin, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpan_critere_entre_deux_dateLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDate_debut, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jpan_critere_entre_deux_dateLayout.setVerticalGroup(
            jpan_critere_entre_deux_dateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpan_critere_entre_deux_dateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpan_critere_entre_deux_dateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpan_critere_entre_deux_dateLayout.createSequentialGroup()
                        .addComponent(jDate_debut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(jDate_fin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpan_critere_entre_deux_dateLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addGap(10, 10, 10))
        );

        jLabel4.setText("Séléctionner votre choix");

        j_combo_select_critere.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Séléctionner" }));

        javax.swing.GroupLayout jpan_critere_combo_lot_et_utilisateurLayout = new javax.swing.GroupLayout(jpan_critere_combo_lot_et_utilisateur);
        jpan_critere_combo_lot_et_utilisateur.setLayout(jpan_critere_combo_lot_et_utilisateurLayout);
        jpan_critere_combo_lot_et_utilisateurLayout.setHorizontalGroup(
            jpan_critere_combo_lot_et_utilisateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpan_critere_combo_lot_et_utilisateurLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(j_combo_select_critere, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpan_critere_combo_lot_et_utilisateurLayout.setVerticalGroup(
            jpan_critere_combo_lot_et_utilisateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpan_critere_combo_lot_et_utilisateurLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jpan_critere_combo_lot_et_utilisateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(j_combo_select_critere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_valider_recherche.setText("Valider");
        btn_valider_recherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_valider_rechercheActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(btn_valider_recherche, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btn_valider_recherche, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpanel_en_teteLayout = new javax.swing.GroupLayout(jpanel_en_tete);
        jpanel_en_tete.setLayout(jpanel_en_teteLayout);
        jpanel_en_teteLayout.setHorizontalGroup(
            jpanel_en_teteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_en_teteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpanel_en_teteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanel_en_teteLayout.createSequentialGroup()
                        .addComponent(j_combo_critere, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addComponent(jlabel_base_source, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jpan_critere_entre_deux_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpan_critere_combo_lot_et_utilisateur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpanel_en_teteLayout.setVerticalGroup(
            jpanel_en_teteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpan_critere_entre_deux_date, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_en_teteLayout.createSequentialGroup()
                .addGroup(jpanel_en_teteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpanel_en_teteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpanel_en_teteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jpan_critere_combo_lot_et_utilisateur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpanel_en_teteLayout.createSequentialGroup()
                                .addComponent(jlabel_base_source)
                                .addGap(18, 18, 18)
                                .addComponent(j_combo_critere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );

        jpanel_pers_physique.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Demande Personne Physique", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Narrow", 1, 18))); // NOI18N
        jpanel_pers_physique.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N

        jTable_personne_phys.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_personne_phys);

        javax.swing.GroupLayout jpanel_pers_physiqueLayout = new javax.swing.GroupLayout(jpanel_pers_physique);
        jpanel_pers_physique.setLayout(jpanel_pers_physiqueLayout);
        jpanel_pers_physiqueLayout.setHorizontalGroup(
            jpanel_pers_physiqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_pers_physiqueLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jpanel_pers_physiqueLayout.setVerticalGroup(
            jpanel_pers_physiqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_pers_physiqueLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jpanel_pers_morale.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Demande Personne Morale", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Narrow", 1, 18))); // NOI18N
        jpanel_pers_morale.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N

        javax.swing.GroupLayout jpanel_pers_moraleLayout = new javax.swing.GroupLayout(jpanel_pers_morale);
        jpanel_pers_morale.setLayout(jpanel_pers_moraleLayout);
        jpanel_pers_moraleLayout.setHorizontalGroup(
            jpanel_pers_moraleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1278, Short.MAX_VALUE)
        );
        jpanel_pers_moraleLayout.setVerticalGroup(
            jpanel_pers_moraleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 229, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpanel_en_tete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpanel_pers_physique, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpanel_pers_morale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpanel_en_tete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpanel_pers_physique, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpanel_pers_morale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_valider_rechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_valider_rechercheActionPerformed
        String critere = (String)this.j_combo_critere.getSelectedItem();
        
        System.out.println("Le critère sélectionner est : " + critere);

        
        
    }//GEN-LAST:event_btn_valider_rechercheActionPerformed

    private void j_combo_critereItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_j_combo_critereItemStateChanged
        String selected = "";

        if(evt.getStateChange() == ItemEvent.SELECTED){

            selected += evt.getItem();

            if (selected.equals(c)) {
                 JOptionPane.showMessageDialog(null, "Veuillez selectionner une critère de recherche","Séléction critère", JOptionPane.INFORMATION_MESSAGE);
                 return;
             }
             //Séléctionner une critère de recherche, Par Date, Intervale de date, Par Utilisateurs, Par Lot
             else if (selected.equals("Par Date")) {
                 jDate_fin.setEnabled(false);
                 j_combo_select_critere.setEnabled(false);

                 jDate_debut.setEnabled(true);
             }
             else if (selected.equals("Intervale de date")) {
                 j_combo_select_critere.setEnabled(false);

                 jDate_fin.setEnabled(true);
                 jDate_debut.setEnabled(true);
             }
             else if (selected.equals("Par Utilisateurs")) {
                jDate_fin.setEnabled(false);
                jDate_debut.setEnabled(false);

                j_combo_select_critere.setEnabled(true);
                j_combo_select_critere.removeAllItems();
                j_combo_select_critere.addItem("Séléctionner Utilisateur");
             }
             else {
                jDate_fin.setEnabled(false);
                jDate_debut.setEnabled(false);
                
                j_combo_select_critere.setEnabled(true);
                j_combo_select_critere.removeAllItems();
                j_combo_select_critere.addItem("Séléctionner Lot");
             }
        }
    }//GEN-LAST:event_j_combo_critereItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TraitementImportSaisieCroise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TraitementImportSaisieCroise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TraitementImportSaisieCroise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TraitementImportSaisieCroise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TraitementImportSaisieCroise(BDD_HOST, BDD_PORT, BDD_DBNAME, BDD_USER, BDD_PWD, type_operation).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_valider_recherche;
    private com.toedter.calendar.JDateChooser jDate_debut;
    private com.toedter.calendar.JDateChooser jDate_fin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_personne_phys;
    private javax.swing.JComboBox<String> j_combo_critere;
    private javax.swing.JComboBox<String> j_combo_select_critere;
    private javax.swing.JLabel jlabel_base_source;
    private javax.swing.JPanel jpan_critere_combo_lot_et_utilisateur;
    private javax.swing.JPanel jpan_critere_entre_deux_date;
    private javax.swing.JPanel jpanel_en_tete;
    private javax.swing.JPanel jpanel_pers_morale;
    private javax.swing.JPanel jpanel_pers_physique;
    // End of variables declaration//GEN-END:variables
}
